version: '3.9'

services:
    db:
        container_name: "jira_db"
        image: "postgres:latest"
        environment:
            POSTGRES_DB: "jira_db"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - .:/docker-entrypoint-initdb.d
            - ./postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
            
    pgadmin:
        container_name: "pgadmin"
        image: "dpage/pgadmin4:latest"
        environment:
            PGADMIN_DEFAULT_EMAIL: "email@email.com"
            PGADMIN_DEFAULT_PASSWORD: "password"
        ports:
            - "5050:80"

        